---

- name: "Check if {{ ton_rnode_config_dir }} dir is empty"
  find:
    paths: "{{ ton_rnode_config_dir }}"
    file_type: file
    patterns: '*'
  register: configDirNonEmpty

- name: Delete old configs
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ton_rnode_config_dir }}/config.json"
    - "{{ ton_rnode_config_dir }}/console.json"
    - "{{ ton_rnode_config_dir }}/console_config.json"
  when: configDirNonEmpty is not defined and not configDirNonEmpty

- name: Check TON user (if not exist)
  user:
    name: "{{ ton_node_user }}"
    comment: "TON node user"
    group: "{{ ton_node_group }}"
    shell: /bin/bash
    state: present
  register: ton_user_created

- name: Set home directory variable (if not exist)
  set_fact:
    ton_node_user_home: "{{ ton_user_created.home }}"

- name: Create db dir
  file:
    path: "{{ ton_rnode_db_dir }}"
    state: directory
    owner: "{{ ton_node_user }}"
    group: "{{ ton_node_group }}"
    mode: u=rwx,g=rx,o=

- name: Get ton global config 
  get_url:
    url: "{{ ton_node_global_config_URL_list[ton_node_config].config_URL }}"
    dest: "{{ ton_rnode_config_dir }}"
    owner: "{{ ton_node_user }}"
    group: "{{ ton_node_group }}"
    mode: u=rw,g=r,o=
  when: configDirNonEmpty is not defined and not configDirNonEmpty
  notify: ton_systemd

- name: Config tonos-cli
  command: "{{ item }}"
  args:
    chdir: "{{ ton_node_tools_dir }}"
  loop:
    - "./tonos-cli config endpoint reset"
    - "./tonos-cli config endpoint add {{ ton_node_global_config_URL_list[ton_node_config].DAPP_address }} {{ ton_node_global_config_URL_list[ton_node_config].DAPP_endpoints }}"
    - "./tonos-cli --url {{ ton_node_global_config_URL_list[ton_node_config].DAPP_address }} config"
  when: configDirNonEmpty is not defined and not configDirNonEmpty

- name: Copy tonos-cli.conf.json to configs dir
  copy:
    src: "{{ ton_node_tools_dir }}/tonos-cli.conf.json"
    dest: "{{ ton_rnode_config_dir }}/tonos-cli.conf.json"
    owner: "{{ ton_node_user }}"
    group: "{{ ton_node_group }}"
    mode: u=rw,g=r,o=
    remote_src: yes
  when: configDirNonEmpty is not defined and not configDirNonEmpty

- name: "Set lifetime to 600"
  shell: "{{ item }}"
  become: yes
  become_user: "{{ ton_node_user }}"
  loop:
    - 'jq ".config.lifetime=600" "{{ ton_rnode_config_dir }}/tonos-cli.conf.json" > {{ ton_rnode_config_dir }}/tonos-cli.conf_tmp.json'
    - 'cat {{ ton_rnode_config_dir }}/tonos-cli.conf_tmp.json > {{ ton_rnode_config_dir }}/tonos-cli.conf.json'
  when: configDirNonEmpty is not defined and not configDirNonEmpty

- name: Remove tonos-cli.conf.json in tools dir
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ton_rnode_config_dir }}/tonos-cli.conf_tmp.json"
    - "{{ ton_node_tools_dir }}/tonos-cli.conf.json"

- name: Generate keys (RUST)
  shell: "./keygen > {{ ton_rnode_config_dir }}/{{ ansible_hostname }}_client_keys.json"
  args:
    chdir: "{{ ton_node_tools_dir }}"
    #creates: "{{ ton_rnode_config_dir }}/{{ ansible_hostname }}_client_keys.json"
  become: yes
  become_user: "{{ ton_node_user }}"
  when: configDirNonEmpty is not defined and not configDirNonEmpty

- name: Generate ton_node key config (RUST)
  shell: "{{ ton_node_bin_dir }}/ton_node --configs {{ ton_rnode_config_dir }} --ckey \"$(jq -c .public {{ ton_rnode_config_dir }}/{{ ansible_hostname }}_client_keys.json)\" &"
  #args:
  #  creates: "{{ ton_rnode_config_dir }}/config.json"
  # async: 30
  # poll: 0
  become: yes
  become_user: "{{ ton_node_user }}"
  register: ton_node_key_generated
  when: configDirNonEmpty is not defined and not configDirNonEmpty

- name: Wait for console_config.json creation (RUST)
  wait_for:
    path: "{{ ton_rnode_config_dir }}/console_config.json"
  when: ton_node_key_generated.changed and configDirNonEmpty is not defined and not configDirNonEmpty

- name: Kill nohup ton_node processes
  shell: "kill -9 `jobs -l | awk '{print $2}'`"
  become: yes
  become_user: "{{ ton_node_user }}"
  when: ton_node_key_generated.changed
  ignore_errors: true

- name: Configure console and node ports (RUST)
  shell: "{{ item }}"
  become: yes
  become_user: "{{ ton_node_user }}"
  loop:
    - "jq '.adnl_node.ip_address = \"0.0.0.0:{{ ton_node_adnl_port }}\"' {{ ton_rnode_config_dir }}/config.json > {{ ton_rnode_config_dir }}/config_tmp.json"
    - "jq '.control_server.address = \"127.0.0.1:{{ ton_node_console_port }}\"' {{ ton_rnode_config_dir }}/config_tmp.json > {{ ton_rnode_config_dir }}/config.json"
    - "jq '.server_address = \"127.0.0.1:{{ ton_node_console_port }}\"' {{ ton_rnode_config_dir }}/console_config.json > {{ ton_rnode_config_dir }}/console_config_tmp.json"
    - 'cat {{ ton_rnode_config_dir }}/console_config_tmp.json > {{ ton_rnode_config_dir }}/console_config.json'
  when: configDirNonEmpty is not defined and not configDirNonEmpty

- name: Copy console_template.json (RUST)
  copy:
    src: console_template.json
    dest: "{{ ton_rnode_config_dir }}/console_template.json"
    force: no
    owner: "{{ ton_node_user }}"
    group: "{{ ton_node_group }}"
    mode: u=rw,g=r,o=
  when: configDirNonEmpty is not defined and not configDirNonEmpty

- name: Generate console.json config (RUST)
  shell: "{{ item }}"
  #args:
  #  creates: "{{ ton_rnode_config_dir }}/console.json"
  become: yes
  become_user: "{{ ton_node_user }}"
  loop:
    - "jq \".config = $(cat {{ ton_rnode_config_dir }}/console_config.json)\" {{ ton_rnode_config_dir }}/console_template.json > {{ ton_rnode_config_dir }}/console_tmp.json"
    - "jq \".config.client_key = $(jq .private {{ ton_rnode_config_dir }}/{{ ansible_hostname }}_client_keys.json)\" {{ ton_rnode_config_dir }}/console_tmp.json > {{ ton_rnode_config_dir }}/console.json"
  when: configDirNonEmpty is not defined and not configDirNonEmpty

- name: Delete temp file (RUST)
  file:
    path: "{{ ton_rnode_config_dir }}/{{ item }}"
    state: absent
  loop:
    - console_config_tmp.json
    - console_tmp.json
    - config_tmp.json
    - console_template.json

- name: Set correct keys mode (RUST)
  file:
    path: "{{ item }}"
    state: file
    owner: "{{ ton_node_user }}"
    group: "{{ ton_node_group }}"
    mode: u=rw,g=r,o=
  loop:
    - "{{ ton_rnode_config_dir }}/{{ ansible_hostname }}_client_keys.json"
    - "{{ ton_rnode_config_dir }}/config.json"
    - "{{ ton_rnode_config_dir }}/console.json"
  when: configDirNonEmpty is not defined and not configDirNonEmpty

- name: Firewall block
  block:
    - name: Checking firewalld status
      command: systemctl status firewalld
      ignore_errors: yes
      register: firewalld_node_state

    - name: Open freeton node ports with firewalld
      firewalld:
        immediate: yes
        permanent: yes
        port: "{{ item }}"
        state: enabled
        zone: public
      loop:
        - "{{ ton_node_adnl_port }}/udp"
        - "{{ ton_node_console_port }}/tcp"
      when: "'active (running)' in firewalld_node_state.stdout"
  when: ansible_pkg_mgr == "dnf"

- name: Making Custler scripts env file
  template:
    src: "env.sh.j2"
    dest: "{{ ton_node_scripts }}/env.sh"
    owner: "{{ ton_node_user }}"
    group: "{{ ton_node_group }}"
    mode: u=rwx,g=rx,o=
  when: ton_custler_scripts_enabled

- name: Making Custler telegabot
  template:
    src: "TlgChat.json.sh.j2"
    dest: "{{ ton_node_scripts }}/TlgChat.json.sh"
    owner: "{{ ton_node_user }}"
    group: "{{ ton_node_group }}"
    mode: u=rwx,g=rx,o=
  when: ton_custler_scripts_enabled

- name: Restart ton systemd service
  systemd:
    name: "{{ ton_node_service_name }}"
    state: restarted
    daemon_reload: true
